/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'

// Create Virtual Routes

const SignupLazyImport = createFileRoute('/signup')()
const CreateLazyImport = createFileRoute('/create')()
const IndexLazyImport = createFileRoute('/')()
const MessagesIndexLazyImport = createFileRoute('/messages/')()
const MessagesMessageIdIndexLazyImport = createFileRoute(
  '/messages/$messageId/',
)()
const MessagesSendReceiverIdLazyImport = createFileRoute(
  '/messages/send/$receiverId',
)()

// Create/Update Routes

const SignupLazyRoute = SignupLazyImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/signup.lazy').then((d) => d.Route))

const CreateLazyRoute = CreateLazyImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/create.lazy').then((d) => d.Route))

const IndexLazyRoute = IndexLazyImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))

const MessagesIndexLazyRoute = MessagesIndexLazyImport.update({
  id: '/messages/',
  path: '/messages/',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/messages/index.lazy').then((d) => d.Route),
)

const MessagesMessageIdIndexLazyRoute = MessagesMessageIdIndexLazyImport.update(
  {
    id: '/messages/$messageId/',
    path: '/messages/$messageId/',
    getParentRoute: () => rootRoute,
  } as any,
).lazy(() =>
  import('./routes/messages/$messageId/index.lazy').then((d) => d.Route),
)

const MessagesSendReceiverIdLazyRoute = MessagesSendReceiverIdLazyImport.update(
  {
    id: '/messages/send/$receiverId',
    path: '/messages/send/$receiverId',
    getParentRoute: () => rootRoute,
  } as any,
).lazy(() =>
  import('./routes/messages/send/$receiverId.lazy').then((d) => d.Route),
)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/create': {
      id: '/create'
      path: '/create'
      fullPath: '/create'
      preLoaderRoute: typeof CreateLazyImport
      parentRoute: typeof rootRoute
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupLazyImport
      parentRoute: typeof rootRoute
    }
    '/messages/': {
      id: '/messages/'
      path: '/messages'
      fullPath: '/messages'
      preLoaderRoute: typeof MessagesIndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/messages/send/$receiverId': {
      id: '/messages/send/$receiverId'
      path: '/messages/send/$receiverId'
      fullPath: '/messages/send/$receiverId'
      preLoaderRoute: typeof MessagesSendReceiverIdLazyImport
      parentRoute: typeof rootRoute
    }
    '/messages/$messageId/': {
      id: '/messages/$messageId/'
      path: '/messages/$messageId'
      fullPath: '/messages/$messageId'
      preLoaderRoute: typeof MessagesMessageIdIndexLazyImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexLazyRoute
  '/create': typeof CreateLazyRoute
  '/signup': typeof SignupLazyRoute
  '/messages': typeof MessagesIndexLazyRoute
  '/messages/send/$receiverId': typeof MessagesSendReceiverIdLazyRoute
  '/messages/$messageId': typeof MessagesMessageIdIndexLazyRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexLazyRoute
  '/create': typeof CreateLazyRoute
  '/signup': typeof SignupLazyRoute
  '/messages': typeof MessagesIndexLazyRoute
  '/messages/send/$receiverId': typeof MessagesSendReceiverIdLazyRoute
  '/messages/$messageId': typeof MessagesMessageIdIndexLazyRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexLazyRoute
  '/create': typeof CreateLazyRoute
  '/signup': typeof SignupLazyRoute
  '/messages/': typeof MessagesIndexLazyRoute
  '/messages/send/$receiverId': typeof MessagesSendReceiverIdLazyRoute
  '/messages/$messageId/': typeof MessagesMessageIdIndexLazyRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/create'
    | '/signup'
    | '/messages'
    | '/messages/send/$receiverId'
    | '/messages/$messageId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/create'
    | '/signup'
    | '/messages'
    | '/messages/send/$receiverId'
    | '/messages/$messageId'
  id:
    | '__root__'
    | '/'
    | '/create'
    | '/signup'
    | '/messages/'
    | '/messages/send/$receiverId'
    | '/messages/$messageId/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexLazyRoute: typeof IndexLazyRoute
  CreateLazyRoute: typeof CreateLazyRoute
  SignupLazyRoute: typeof SignupLazyRoute
  MessagesIndexLazyRoute: typeof MessagesIndexLazyRoute
  MessagesSendReceiverIdLazyRoute: typeof MessagesSendReceiverIdLazyRoute
  MessagesMessageIdIndexLazyRoute: typeof MessagesMessageIdIndexLazyRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexLazyRoute: IndexLazyRoute,
  CreateLazyRoute: CreateLazyRoute,
  SignupLazyRoute: SignupLazyRoute,
  MessagesIndexLazyRoute: MessagesIndexLazyRoute,
  MessagesSendReceiverIdLazyRoute: MessagesSendReceiverIdLazyRoute,
  MessagesMessageIdIndexLazyRoute: MessagesMessageIdIndexLazyRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/create",
        "/signup",
        "/messages/",
        "/messages/send/$receiverId",
        "/messages/$messageId/"
      ]
    },
    "/": {
      "filePath": "index.lazy.tsx"
    },
    "/create": {
      "filePath": "create.lazy.tsx"
    },
    "/signup": {
      "filePath": "signup.lazy.tsx"
    },
    "/messages/": {
      "filePath": "messages/index.lazy.tsx"
    },
    "/messages/send/$receiverId": {
      "filePath": "messages/send/$receiverId.lazy.tsx"
    },
    "/messages/$messageId/": {
      "filePath": "messages/$messageId/index.lazy.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
